### PR TITLE
Footer added

### PR DESCRIPTION
**Pull request by Croustys**
https://i.gyazo.com/811452f231fc3854cf1acf345b791593.png updated picture

### CODE REVIEW

**Comment by KonradLinkowski** [comment]
Looks cool, but can you lower the font size? It seems really big compared to text in drop container

**Comment by Croustys** [comment]
Sure thing, gonna adjust a bit and update the PR

**Comment by KonradLinkowski** [comment]
Will merge into the feature branch and fix somethings myself
Grab a free t-shirt quarter

**Comment by Croustys** [comment]
haha cheers

**Pull request merged**
