### PR TITLE
add progress bar

### PR DESCRIPTION
**Pull request by AlbyIanna**
Added a progress bar as per #10

### CODE REVIEW

**Comment by KonradLinkowski** [comment]
That's rather a spinner, not a progress bar unfortunately

**Comment by AlbyIanna** [comment]
Implementing a precise progress bar to estimate the actual progress of the process is rather difficult with this use case. It could be done using a library that implements the Observer/Observable pattern, like [RxJS](https://rxjs-dev.firebaseapp.com/guide/overview), but I don't know if it's worth it. @KonradLinkowski what do you say?

**Comment by KonradLinkowski** [comment]
You can be right that it's difficult. And adding rxjs for a reason like this is an overkill

**Comment by AlbyIanna** [comment]
Another solution could be to implement a fake progress bar, assuming that (with a certain number of points) the image will take approximately a certain time.
For example, we could show a progress bar that fills completely in 10 seconds when the number of points is 1000 and 8 seconds with 800 points(numbers are totally arbitrary in this example).

But honestly, implementing such logic would be as complex as the project itself which is kinda pointless IMO.

If your goal is
> to show that the process is going on

I think that disabling the interface and using a non-determinate progress bar is the way to go.

Let me know what do you think about it 😄

**Comment by KonradLinkowski** [comment]
I made it in #12 with service worker

**Comment by AlbyIanna** [comment]
@KonradLinkowski Nice!

**Comment by AlbyIanna** [comment]
@KonradLinkowski It'd be really great from you if you'd add the `hacktoberfest-accepted` label on this 😄 
But I won't insist if you don't want to

**Pull request closed without merging**
